### ISSUE TITLE
l4d2_stats translation 

### ISSUE THREAD

**Issue by fantasylidong** [lechuga16/L4D2-Competitive-Translation#1]
Hello, lechuga16,
In l4d2_stats.sp
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/68f23c217c1d6eeb8f445c6c3de06a10f1d53f76/addons/sourcemod/scripting/l4d2_stats.sp#L434-L440

assister_string should also consider as a translation item.

otherwise, a little wired combind english and translation phrases.

**Comment by lechuga16** [comment]
You're right, it would be a good idea for that detail to be defined in the translation.

**Comment by fantasylidong** [comment]
[in](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4fc8050a23c5a0ae22e6a6ac4b68071574a098d9/addons/sourcemod/translations/tank_rush.phrases.txt#L11-L14)

unfreeze should be tank died, unfreeze distance points
{red}Tank {default}is dead. {olive}Unfreezing {default}distance points!

**Comment by lechuga16** [comment]
it was fixed, thanks

**Comment by fantasylidong** [comment]
> it was fixed, thanks

Still not complete fix it.
Unfreeze is caused by tank death, not tank spawn.

**Comment by lechuga16** [comment]
you're right, it's another oversight on my part. 
https://github.com/lechuga16/L4D2-Competitive-Translation/commit/ba3e5d86cbbdb1941e1d2e4df5bc3af13e6c0361
